---
platform: srx

my_host_name:
    mtdew

my_domain_name:
    lab

management:
    ifd: ge-0/0/0
    ip: 192.168.100.26
    subnet_bits: 24

local_timezone:
    America/New_York

syslog_prefix:
    MTDEW

packet_based:
    False
